env:
  node: true
extends: 'eslint:recommended'
plugins:
  - mocha
parserOptions:
  ecmaVersion: 6
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  mocha/no-exclusive-tests:
    - error
    - always
